DROP DATABASE SSEF;

CREATE DATABASE SSEF;
USE SSEF;

CREATE TABLE PDFDATA (
	SSEFCode varchar(5),
	ProjectTitle5 varchar(50),
	StudentName4 varchar(100),
	StudentName varchar(50),
	
	-- Form 1
	ReviewRules boolean,
	ChecklistReview boolean,
	WorkedWithStudent boolean,
	PriorApprovalRequired boolean,
	Humans boolean,
	Vertebrates boolean,
	Microorganisms boolean,
	rDNA boolean,
	Tissues boolean,
	AllProjectItems boolean,
	AdultSponsorChecklist boolean,
	ResearchPlan boolean,
	StudentChecklist boolean,
	ApprovalForm boolean,
	ResearchInst boolean,
	ContinForm boolean,
	IncHumans boolean,
	HumanSub boolean,
	SampleInformedConsent boolean,
	QualSciForm boolean,
	VAnimals boolean,
	VT5A boolean,
	VT5B boolean,
	VTQS boolean,
	PotHaz boolean,
	PH6A boolean,
	PH6B boolean,
	PHQS boolean,
	PHRisk boolean,
	HAZ boolean,
	HazRisk boolean,
	HazQS boolean,
	ASPrinted varchar(50),
	ASDateofReview varchar(10),
	ASPhone varchar(15),
	ASEmail varchar(50),
	
	-- Form 1A
	1ATeamLeader varchar(50),
	1AGrade varchar(15),
	1AEmail varchar(40),
	1APhone varchar(15),
	TeamMember2 varchar(50),
	TeamMember3 varchar(50),
	ProjectTitle varchar(50),
	ProjectTitle2 varchar(50),
	1ASchool varchar(50),
	1ASchoolPhone varchar(15),
	1ASchoolAdd1 varchar(50),
	1ASchoolAdd2 varchar(50),	
	1AAdultSpon varchar(50),
	1AASEmail varchar(50),
	SCContinue0 boolean,
	SCContinue1 boolean,
	SCAbstract boolean,
	SCResPlan boolean,
	CF7 boolean,
	SCActStart varchar(10),
	SCActEnd varchar(10),
	SCResInst boolean,
	SCSchool boolean,
	SCfield boolean,
	SCHome boolean,
	SCOther boolean,
	SCOtherExpl varchar(50),
	SCNonName1 varchar(50),
	SCNonAdd1A varchar(50),
	SCNonAdd1B varchar(50),
	SCNonPhone1 varchar(15),
	SCNonName2 varchar(50),
	SCNonAdd2A varchar(50),
	SCNonAdd2B varchar(50),
	SCNonPhone2 varchar(15),
		
	-- Form 1B
	1BStudentPrinted varchar(50),
	1BDateAck varchar(10),
	1BParentName varchar(50),
	1BDateApp varchar(10),
	1BSRCPrinted varchar(50),
	1BSRCIRBAppDate varchar(10),
	1BSRCChairPrinted varchar(50),
	1BSRCChairDate varchar(10),
	1BRegSsRCChairPrinted varchar(50),
	1BSRCChairAppDate varchar(10),
	1BStateSRCChairPrinted varchar(50),
	1BStateSRCChairDate varchar(10),
	
	-- Form 1C
	1CUseEquip boolean,
	1CPerformExp boolean,
	1CSubset0 boolean,
	1CSubset1 boolean,
	1CRulesReview0 boolean,
	1CRulesReview1 boolean,
	1CGetIdea varchar(300),
	1cGroupExp0 boolean,
	1CGroupExp1 boolean,
	1CGroupExp varchar(300),
	1CSpecificProcs varchar(300),
	1CCreative varchar(300),
	1CSAPrinted varchar(50),
	1CSATitle varchar(50),
	1CSAInstitution varchar(500),
	1CSADateSigned varchar(10),
	1CSAAddress varchar(100),
	1CSAEmail varchar(50),
		
	-- Form 2
	QSName varchar(50),
	QSEducation varchar(50),
	QSDegrees varchar(75),
	QSSuperTraining varchar(150),
	QSPosition varchar(50),
	QSInstitution varchar(50),
	QSAddress varchar(100),
	QSEmail varchar(50),
	QSRuleReview0 boolean,
	QSRuleReview1 boolean,
	QSHumans0 boolean,
	QSHumans1 boolean,
	QSVert0 boolean,
	QSVert1 boolean,
	QSHazard0 boolean,
	QSHazard1 boolean,
	QSControl0 boolean,
	QSControl1 boolean,
	QSSubset0 boolean,
	QSSubset1 boolean,
	QSSuper0 boolean,
	QSSuper1 boolean,
	QSWhoSuper varchar(50),
	QSDSTraining varchar(150),
	QSPrinted varchar(50),
	ApprovalDate varchar(10),
	QSDSPrinted varchar(50),
	QSDSApprovalDate varchar(10),
	QSDSPhone varchar(15),
	QSDSEmail varchar(50),

	-- Form 3
	RAIDHazards varchar(150),
	RAIDAssess varchar(150),
	RASafety varchar(150),
	RADisposal varchar(150),
	RAResources varchar(150),
	RAQSPrinted varchar(50),
	RAQSReviewDate varchar(10),
	RAQSPosition varchar(50),
	RAQSEmail varchar(50),
	RAQSTraining varchar(150),

	-- Form 4
	HSAS varchar(50),
	HSASEmail varchar(50),
	HSSubmitResPlan boolean,
	HSAttachSurvey boolean,
	LegalInstrument boolean,
	HSInformedConsentAttached boolean,
	HSWorkingQS0 boolean,
	HSWorkingQS1 boolean,
	notapproved boolean,
	Projectapproved boolean,
	Minimalrisk boolean,
	morethanminimal boolean,
	QSyes boolean,
	qsno boolean,
	writtenminorassentyes boolean,
	minorassentno boolean,
	minorassentNA boolean,
	parentalyes boolean,
	parentalno boolean,
	ParentalNA boolean,
	18yes boolean,
	18no boolean,
	18NA boolean,
	HSIRBPrinted1 varchar(50),
	HSIRBDegree1 varchar(50),
	HSIRBDATE varchar(10),
	HSIRBPrinted2 varchar(50),
	HSIRBDegree2 varchar(50),
	HSIRB2date varchar(10),
	HSIRBPrinted3 varchar(50),
	HSIRBDegree3 varchar(50),
	HSIRB3date varchar(10),

	-- Human Informed Consent Form
	CFPurpose varchar(150),
	CFAskedTo1 varchar(150),
	CFTimeRequired varchar(100),
	CFRisks1 varchar(100),
	CFBenefits varchar(150),
	CFConfidentiality1 varchar(150),
	CFAdultSponsor varchar(50),
	CFASEmail varchar(50),
	CFParticipantPrinted varchar(50),
	CFParentAssentDate varchar(10),
	CFParentAssentPrinted varchar(50),
	CFAdultAssentDate varchar(10),
		
	-- Form 5A
	5ACommonName varchar(75),
	5AHousing varchar(150),
	5AAftermath varchar(150),
	DSrequired boolean,
	VandDSrequired boolean,
	VDSQSRequired boolean,
	5ASRCChairPrinted varchar(50),
	SRCChair5adate varchar(10),
	Vcert boolean,
	Vcertdoses boolean,
	Vcare boolean,
	5AVetPrinted varchar(50),
	5AVetEmail varchar(50),
	Vapprovaldate varchar(10),
	5aDSreview boolean,
	5aDAcert boolean,
	5ADSPrinted varchar(50),
	5ADSEmail varchar(50),
	5adsdate varchar(10),


	
	-- Form 5B
	5BProtocolNumber varchar(50),
	5BSpeciesUsed varchar(75),
	5BNumberUse varchar(4),
	5BStudentrole varchar(150),
	5BDeath varchar(150),
	5BTissueUse0 boolean,
	5BTissueUse1 boolean,
	5BLabTraining varchar(150),
	5BQSPIPrintedName varchar(75),
	5bqspidate varchar(10),

	
	-- Form 6A
	6ABiologicAgents varchar(150),
	6ASite varchar(150),
	6AMinimizeRisk varchar(150),
	6ABiosafetyLevel varchar(150),
	6ADisposal varchar(150),
	6AQSStudentTraining varchar(150),
	6AConcur0 boolean,
	6AConcur1 boolean,
	6AConcurExp varchar(100),
	6asrcbsl1 boolean,
	6absl1date varchar(10),
	6aSRCbsl2 boolean,
	6absl2date varchar(10),
	6aSRCIACUC boolean,
	6aiacucdate varchar(10),
	6anoapprovalrequired boolean,
	6asrcapproval varchar(10),
	6aSRCChairPrintedName varchar(50),
	
	-- Form 6B
	6BFresh boolean,
	6BOrgan boolean,
	6BBlood boolean,
	6BBodyFluids boolean,
	6BPrimary boolean,
	6BHuman boolean,
	6BTissuesObtained varchar(150),
	6BInstitutionObtained varchar(150),
	6bqstissuesverify boolean,
	6boshealthact boolean,
	6BQSPrinted varchar(50),
	6bqsdate varchar(10),
	6BQSTitle varchar(50),
	6BQSEmail varchar(50),
	6BQSInstitution varchar(50),
		
	-- Form 7
	7CurrTitle varchar(75),
	70708Title varchar(75),
	70809Title varchar(75),
	7CurrObj varchar(150),
	70708Obj varchar(150),
	70809Obj varchar(150),
	7CurrTheme varchar(150),
	70708Theme varchar(150),
	70809Theme varchar(150),
	7CurrVar varchar(150),
	70708Var varchar(150),
	70809Var varchar(150),
	7CurrChg varchar(150),
	70708Chg varchar(150),
	70809Chg varchar(150),
	1112Ab boolean,
	1213Ab boolean,	
	StudentsName varchar(100),
	7SigDate varchar(10),
		
	PRIMARY KEY (SSEFCode)
);